// packages/headless-audioplayer-svelte/src/lib/PlayerSlider.svelte
<script lang="ts">
  import type { Writable } from "svelte/store";

  export let onChange: (e: Event) => void;
  export let progress: Writable<number>;
  export let downloadProgress: number;
  export let containerColor: string = "#f4f4f5";
  export let thumbColor: string = "#18181b";
  export let progressColor: string = "#18181b";
  export let downloadProgressColor: string = "#e4e4e7";

  let position = 0;
  let marginLeft = 0;
  let progressBarWidth = 0;
  let rangeRef: HTMLInputElement;
  let thumbRef: HTMLSpanElement;

  progress.subscribe((value) => {
    if (rangeRef && thumbRef) {
      const thumbWidth = thumbRef.getBoundingClientRect().width;
      const rangeWidth = rangeRef.getBoundingClientRect().width;
      const centerThumb = (thumbWidth / 100) * value * -1;
      const centerProgressBar =
        thumbWidth + (rangeWidth / 100) * value - (thumbWidth / 100) * value;
      position = value;
      marginLeft = centerThumb;
      progressBarWidth = centerProgressBar;
    }
  });
</script>

<div
  class="headless-player-progress-container"
  style={`background-color: ${containerColor}`}
>
  <span
    class="headless-player-progress-bar"
    style={`width: ${progressBarWidth}px; background-color: ${progressColor}`}
  />
  <span
    bind:this={thumbRef}
    class="headless-player-thumb"
    style={`left: ${position}%; margin-left: ${marginLeft}px; background-color: ${thumbColor}`}
  />
  <span
    class="headless-player-download"
    style={`background-color: ${downloadProgressColor}; width: ${downloadProgress}%`}
  />
  <input
    type="range"
    class="headless-player-range"
    step="0.01"
    bind:this={rangeRef}
    value={position}
    on:change={onChange}
  />
</div>

<style scoped>
  .headless-player-progress-container {
    display: block;
    width: 100%;
    border-radius: 0.375rem;
    position: relative;
    height: 10px;
  }

  .headless-player-progress-bar {
    height: 100%;
    position: relative;
    display: block;
    border-radius: 0.375rem;
    z-index: 20;
  }

  .headless-player-thumb {
    width: 16px;
    height: 16px;
    border-radius: 100px;
    transform: translateY(-50%);
    position: absolute;
    top: 50%;
    margin-top: auto;
    margin-bottom: auto;
    pointer-events: none;
    user-select: none;
    z-index: 20;
  }

  .headless-player-download {
    height: 10px;
    border-radius: 100px;
    transform: translateY(-50%);
    position: absolute;
    top: 50%;
    margin-top: auto;
    margin-bottom: auto;
    pointer-events: none;
    user-select: none;
    z-index: 10;
    transition: width 150ms;
  }

  .headless-player-range::-moz-range-thumb,
  .headless-player-range::-ms-thumb,
  .headless-player-range::-webkit-slider-thumb {
    width: 16px;
    height: 16px;
    border-radius: 100%;
    cursor: pointer;
    -webkit-appearance: none;
    appearance: none;
  }

  .headless-player-range {
    appearance: none;
    height: 10px;
    width: 100%;
    cursor: pointer;
    position: absolute;
    margin-left: 0;
    margin-right: 0;
    margin-top: auto;
    margin-bottom: auto;
    top: 0;
    bottom: 0;
    opacity: 0;
    z-index: 30;
  }
</style>

// packages/headless-audioplayer-react/PlayerSlider.tsx
import { ChangeEventHandler, useEffect, useRef, useState } from "react";

type Props = {
  onChange: ChangeEventHandler<HTMLInputElement>;
  progress: number;
  downloadProgress: number;
};

export const PlayerSlider = ({
  onChange,
  progress,
  downloadProgress,
}: Props) => {
  const [position, setPosition] = useState(0);
  const [marginLeft, setMarginLeft] = useState(0);
  const [progressBarWidth, setProgressBarWidth] = useState(0);

  const rangeRef = useRef<HTMLInputElement>(null);
  const thumbRef = useRef<HTMLSpanElement>(null);

  useEffect(() => {
    if (rangeRef.current && thumbRef.current) {
      const thumbWidth = thumbRef.current.getBoundingClientRect().width;
      const rangeWidth = rangeRef.current.getBoundingClientRect().width;
      const centerThumb = (thumbWidth / 100) * progress * -1;
      const centerProgressBar =
        thumbWidth +
        (rangeWidth / 100) * progress -
        (thumbWidth / 100) * progress;
      setPosition(progress);
      setMarginLeft(centerThumb);
      setProgressBarWidth(centerProgressBar);
    }
  }, [progress]);

  return (
    <div className="block w-full h-2 bg-gray-100 rounded-md relative">
      <span
        className="h-full bg-gradient-to-r from-zinc-700 to-zinc-900 relative block rounded-md z-20"
        style={{ width: `${progressBarWidth}px` }}
      ></span>
      <span
        className="w-4 h-4 rounded-full bg-zinc-900 -translate-y-2/4 absolute top-2/4 my-auto pointer-events-none select-none z-20"
        ref={thumbRef}
        style={{
          left: `${position}%`,
          marginLeft: `${marginLeft}px`,
        }}
      ></span>
      <span
        className="h-2 rounded-full bg-gray-200 -translate-y-2/4 absolute top-2/4 my-auto pointer-events-none select-none z-10 transition-[width] duration-150"
        style={{ width: `${downloadProgress}%` }}
      ></span>
      <input
        type="range"
        className="range appearance-none h-4 w-full cursor-pointer mx-0 my-auto absolute top-0 bottom-0 opacity-0 z-30"
        step="0.01"
        ref={rangeRef}
        value={position}
        onChange={onChange}
      />
    </div>
  );
};
