// packages/headless-audioplayer-react/Player.tsx
import {
  useState,
  useRef,
  useEffect,
  ChangeEvent,
  createContext,
  ReactNode,
  SyntheticEvent,
} from "react";

type MutedProps = {
  state: "muted" | "off";
  backVolume: number;
};

type PlayerContextProps = {
  downloadProgress: number;
  isPlaying: boolean;
  progress: number;
  timestamp: {
    current: string;
    total: string;
  };
  togglePlay: () => void;
  onSliderChange: (e: ChangeEvent<HTMLInputElement>) => void;
  decreaseVolume: () => void;
  increaseVolume: () => void;
  volume: number;
  onSliderVolumeChange: (e: ChangeEvent<HTMLInputElement>) => void;
  toggleMute: () => void;
  mute: MutedProps;
};
const PlayerContext = createContext<PlayerContextProps>({
  downloadProgress: 0,
  isPlaying: false,
  onSliderChange: (e: ChangeEvent<HTMLInputElement>) => {},
  progress: 0,
  timestamp: { current: "0", total: "0" },
  togglePlay: () => {},
  decreaseVolume: () => {},
  increaseVolume: () => {},
  volume: 0,
  onSliderVolumeChange: () => {},
  toggleMute: () => {},
  mute: { backVolume: 1, state: "off" },
});

const getTime = (time: number) => {
  let seconds: string | number = time % 60;
  const foo = time - seconds;
  const minutes = foo / 60;
  if (seconds < 10) {
    seconds = `0${seconds.toFixed(0)}`;
  } else {
    seconds = seconds.toFixed(0);
  }
  return minutes + ":" + seconds;
};

const usePlayer = (src: string) => {
  const [isPlaying, setIsPlaying] = useState(false);
  const [progress, setProgress] = useState(0);
  const [shouldStart, setShouldStart] = useState(false);
  const [timestamp, setTimeStamp] = useState({ current: "0:0", total: "0:0" });
  const [downloadProgress, setDownloadProgress] = useState(0);
  const [muted, setIsMuted] = useState<MutedProps>({
    state: "off",
    backVolume: 1,
  });
  const [volume, setVolume] = useState(0);
  const audioEl = useRef<HTMLAudioElement>(null);

  const onSliderChange = (e: ChangeEvent<HTMLInputElement>) => {
    if (audioEl.current) {
      const audio = audioEl.current;
      const updatedCurrentTime =
        (audio.duration / 100) * Number(e.target.value);
      audio.currentTime = updatedCurrentTime;
      setProgress(Number(e.target.value));
    }
  };

  const onSliderVolumeChange = (e: ChangeEvent<HTMLInputElement>) => {
    if (audioEl.current) {
      const newValue = Number(e.target.value) / 100;
      if (newValue > 1 || newValue < 0) return;
      audioEl.current.volume = newValue;
      setVolume(newValue);
    }
  };

  const toggleMute = () => {
    if (audioEl.current) {
      if (muted.state == "muted") {
        if (muted.backVolume == 0) {
          audioEl.current.volume = 1;
          setIsMuted({ state: "off", backVolume: audioEl.current.volume });
          setVolume(audioEl.current.volume);
        } else {
          audioEl.current.volume = muted.backVolume;
          setIsMuted({ state: "off", backVolume: audioEl.current.volume });
          setVolume(audioEl.current.volume);
        }
      } else {
        setIsMuted({ state: "muted", backVolume: audioEl.current.volume });
        audioEl.current.volume = 0;
        setVolume(audioEl.current.volume);
      }
    }
  };

  const increaseVolume = () => {
    if (audioEl.current) {
      if (audioEl.current.volume + 0.1 <= 1) {
        audioEl.current.volume = audioEl.current.volume + 0.1;
        setVolume(audioEl.current.volume);
        // @ts-ignore
        setIsMuted((prev) => ({ ...prev, backVolume: audioEl.current.volume }));
      } else {
        audioEl.current.volume = 1;
        setVolume(audioEl.current.volume);
        // @ts-ignore
        setIsMuted((prev) => ({ ...prev, backVolume: audioEl.current.volume }));
      }
    }
  };

  const decreaseVolume = () => {
    if (audioEl.current) {
      if (audioEl.current.volume - 0.1 >= 0) {
        audioEl.current.volume = audioEl.current.volume - 0.1;
        setVolume(audioEl.current.volume);
        // @ts-ignore
        setIsMuted((prev) => ({ ...prev, backVolume: audioEl.current.volume }));
      } else {
        audioEl.current.volume = 0;
        setVolume(audioEl.current.volume);
        // @ts-ignore
        setIsMuted((prev) => ({ ...prev, backVolume: audioEl.current.volume }));
      }
    }
  };

  useEffect(() => {
    if (audioEl.current) {
      if (isPlaying) {
        audioEl.current.play();
        setShouldStart(true);
      } else {
        audioEl.current.pause();
        setShouldStart(false);
      }
    }
  }, [isPlaying, src]);

  useEffect(() => {
    setTimeStamp({ current: "0:0", total: "0:0" });
    if (audioEl.current) {
      setVolume(audioEl.current.volume);
      if (audioEl.current.currentTime && audioEl.current.duration) {
        const currentTime = getTime(audioEl.current.currentTime);
        const totalTime = getTime(audioEl.current.duration);
        if (!currentTime || !totalTime) {
          setTimeStamp({ current: "0:00", total: "0:00" });
        } else {
          setTimeStamp({ current: currentTime, total: totalTime });
        }
      }
    }
    if (shouldStart) {
      setIsPlaying(true);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const togglePlay = () => {
    setIsPlaying((prev) => !prev);
  };

  const onTimeUpdate = (e: ChangeEvent<HTMLAudioElement>) => {
    const percent = (
      (e.currentTarget.currentTime / e.currentTarget.duration) *
      100
    ).toFixed(2);
    setProgress(+percent);
    if (e.currentTarget.currentTime && e.currentTarget.duration) {
      const currentTime = getTime(e.currentTarget.currentTime);
      const totalTime = getTime(e.currentTarget.duration);
      if (!currentTime || !totalTime) {
        setTimeStamp({ current: "0:00", total: "0:00" });
      } else {
        setTimeStamp({ current: currentTime, total: totalTime });
      }
    } else {
      setTimeStamp({ current: "0:00", total: "0:00" });
    }
  };

  const handleOnDownloadProgress = () => {
    const audio = audioEl.current;
    if (downloadProgress <= 100 && audio) {
      for (let i = 0; i < audio.buffered.length; i++) {
        const bufferedStart = audio.buffered.start(i);
        const bufferedEnd = audio.buffered.end(i);
        setDownloadProgress(
          Math.round((100 / audio.duration) * (bufferedEnd - bufferedStart)) ||
            0
        );
      }
    }
  };

  return {
    audioEl,
    isPlaying,
    progress,
    timestamp,
    onSliderChange,
    onTimeUpdate,
    handleOnDownloadProgress,
    downloadProgress,
    togglePlay,
    volume,
    increaseVolume,
    decreaseVolume,
    onSliderVolumeChange,
    toggleMute,
    mute: muted,
  };
};

export type PlayerProps = {
  src: string;
  onEnded?: (e: SyntheticEvent<HTMLAudioElement, Event>) => void;
  onPause?: (e: SyntheticEvent<HTMLAudioElement, Event>) => void;
  onPlay?: (e: SyntheticEvent<HTMLAudioElement, Event>) => void;
  loop?: boolean;
  children: ReactNode;
};

const PlayerProvider = ({
  src,
  children,
  onEnded,
  onPause,
  onPlay,
  ...rest
}: PlayerProps) => {
  const {
    audioEl,
    downloadProgress,
    handleOnDownloadProgress,
    isPlaying,
    onSliderChange,
    onTimeUpdate,
    progress,
    timestamp,
    togglePlay,
    decreaseVolume,
    increaseVolume,
    volume,
    onSliderVolumeChange,
    toggleMute,
    mute,
  } = usePlayer(src);

  return (
    <PlayerContext.Provider
      value={{
        downloadProgress,
        isPlaying,
        progress,
        timestamp,
        togglePlay,
        onSliderChange,
        decreaseVolume,
        increaseVolume,
        volume,
        onSliderVolumeChange,
        toggleMute,
        mute,
      }}
    >
      <audio
        src={src}
        onProgress={handleOnDownloadProgress}
        onTimeUpdate={onTimeUpdate}
        onEnded={onEnded}
        onPause={onPause}
        onPlay={onPlay}
        ref={audioEl}
        controls={false}
        style={{ display: "none" }}
        {...rest}
      ></audio>
      {children}
    </PlayerContext.Provider>
  );
};

const Player = PlayerContext.Consumer;

export { PlayerProvider, Player };

// packages/headless-audioplayer-svelte/src/lib/Player.svelte
<script lang="ts">
  import { onMount, setContext } from "svelte";
  import { writable, type Writable } from "svelte/store";
  import type { PlayerContextProps } from "./index";

  export let src: Writable<string>;
  export let onEnded: (e: Event) => void = () => {};
  export let onPause: (e: Event) => void = () => {};
  export let onPlay: (e: Event) => void = () => {};
  export let loop: boolean = false;

  const getTime = (time: number) => {
    let seconds: string | number = time % 60;
    const foo = time - seconds;
    const minutes = foo / 60;
    if (seconds < 10) {
      seconds = `0${seconds.toFixed(0)}`;
    } else {
      seconds = seconds.toFixed(0);
    }
    return minutes + ":" + seconds;
  };

  let isPlaying = writable(false);
  let progress = writable(0);
  let shouldStart = writable(false);
  let timestamp = writable({ current: "0:0", total: "0:0" });
  let downloadProgress = writable(0);
  let volume = writable(0);
  const muted = writable<{ state: "off" | "muted"; backVolume: number }>({
    state: "off",
    backVolume: 1,
  });
  let audioEl: HTMLAudioElement;

  onMount(() => {
    if (audioEl) {
      $volume = audioEl.volume;
      if (audioEl.currentTime && audioEl.duration) {
        const currentTime = getTime(audioEl.currentTime);
        const totalTime = getTime(audioEl.duration);
        if (!currentTime || !totalTime) {
          $timestamp = { current: "0:00", total: "0:00" };
        } else {
          $timestamp = { current: currentTime, total: totalTime };
        }
      }
    }
    if ($shouldStart) {
      $isPlaying = true;
    }
  });

  const onSliderChange = (e: Event) => {
    const event = e.target as HTMLInputElement;
    if (audioEl) {
      const newValue = Number(event.value);
      const updatedCurrentTime = (audioEl.duration / 100) * newValue;
      audioEl.currentTime = updatedCurrentTime;
      $progress = newValue;
    }
  };

  const onSliderVolumeChange = (e: Event) => {
    const event = e.target as HTMLInputElement;
    if (audioEl) {
      const newValue = Number(event.value) / 100;
      if (newValue > 1 || newValue < 0) return;
      audioEl.volume = newValue;
      $volume = newValue;
    }
  };

  const toggleMute = () => {
    if (audioEl) {
      if ($muted.state == "muted") {
        if ($muted.backVolume == 0) {
          audioEl.volume = 1;
          $muted = { state: "off", backVolume: audioEl.volume };
          $volume = audioEl.volume;
        } else {
          audioEl.volume = $muted.backVolume;
          $muted = { state: "off", backVolume: audioEl.volume };
          $volume = audioEl.volume;
        }
      } else {
        $muted = { state: "muted", backVolume: audioEl.volume };
        audioEl.volume = 0;
        $volume = audioEl.volume;
      }
    }
  };

  const increaseVolume = () => {
    if (audioEl) {
      if (audioEl.volume + 0.1 <= 1) {
        audioEl.volume = audioEl.volume + 0.1;
        $volume = audioEl.volume;
        $muted = { ...$muted, backVolume: audioEl.volume };
      } else {
        audioEl.volume = 1;
        $volume = audioEl.volume;
        $muted = { ...$muted, backVolume: audioEl.volume };
      }
    }
  };

  const decreaseVolume = () => {
    if (audioEl) {
      if (audioEl.volume - 0.1 >= 0) {
        audioEl.volume = audioEl.volume - 0.1;        
        $volume = audioEl.volume;
        $muted = { ...$muted, backVolume: audioEl.volume };
      } else {
        audioEl.volume = 0;
        $volume = audioEl.volume;
        $muted = { ...$muted, backVolume: audioEl.volume };
      }
    }
  };

  isPlaying.subscribe((value) => {
    if (audioEl) {
      if (value) {
        audioEl.play();
        $shouldStart = true;
      } else {
        audioEl.pause();
        $shouldStart = false;
      }
    }
  });

  src.subscribe((value) => {    
    $progress = 0;
    $downloadProgress = 0;
    setTimeout(() => {
      if (audioEl) {
        if ($isPlaying) {
          audioEl.play();
          $shouldStart = true;
        } else {
          audioEl.pause();
          $shouldStart = false;
        }
      }
    }, 500);
  });

  const togglePlay = () => {
    $isPlaying = !$isPlaying;
  };

  const onTimeUpdate = (e: Event) => {
    const event = e.target as HTMLAudioElement;
    // @ts-ignore
    if (event.currentTime && event.duration && event.duration != NaN) {
      const percent = ((event.currentTime / event.duration) * 100).toFixed(2);
      $progress = +percent;
      const currentTime = getTime(event.currentTime);
      const totalTime = getTime(event.duration);
      if (!currentTime || !totalTime) {
        $timestamp = { current: "0:00", total: "0:00" };
      } else {
        $timestamp = { current: currentTime, total: totalTime };
      }
    } else {
      $timestamp = { current: "0:00", total: "0:00" };
    }
  };

  const handleOnDownloadProgress = () => {
    if ($downloadProgress <= 100 && audioEl) {
      for (let i = 0; i < audioEl.buffered.length; i++) {
        const bufferedStart = audioEl.buffered.start(i);
        const bufferedEnd = audioEl.buffered.end(i);
        $downloadProgress =
          Math.round(
            (100 / audioEl.duration) * (bufferedEnd - bufferedStart)
          ) || 0;
      }
    }
  };

  setContext<PlayerContextProps>("playerContext", {
    isPlaying,
    downloadProgress,
    progress,
    timestamp,
    volume,
    onSliderChange,
    onSliderVolumeChange,
    increaseVolume,
    decreaseVolume,
    togglePlay,
    mute: muted,
    toggleMute
  });
</script>

<audio
  src={$src}
  bind:this={audioEl}
  on:timeupdate={onTimeUpdate}
  on:progress={handleOnDownloadProgress}
  on:play={onPlay}
  on:pause={onPause}
  on:ended={onEnded}
  {loop}
/>
<slot />
